import { FormEvent, useEffect, useMemo, useState } from 'react';
import { BarChart3, CheckCircle2, Search, Users, XCircle } from 'lucide-react';
import { cn } from './lib/utils';
import { supabase } from './lib/supabase';

type Member = { name: string; ic: string; phone: string; memberId: string; term: string; expiry: string; branch: string; active: boolean };
type Row = Record<string, string>;
type Payload = { members: Member[]; family: Row[]; vendors: Row[]; isAdmin: boolean };

export default function TeamAra({ canEdit }: { canEdit: boolean }) {
  const [tab, setTab] = useState<'check' | 'dashboard' | 'directory' | 'partners'>('check');
  const [query, setQuery] = useState(''); const [submitted, setSubmitted] = useState('');
  const [data, setData] = useState<Payload>({ members: [], family: [], vendors: [], isAdmin: canEdit });
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async (search = submitted) => { if (!supabase) { setError('Supabase is not configured.'); return; } setLoading(true); setError(''); try { const { data: session } = await supabase.auth.getSession(); if (!session.session) throw new Error('Please sign in again.'); const response = await fetch(`/api/panel-files?resource=teamara${search ? `&q=${encodeURIComponent(search)}` : ''}`, { headers: { Authorization: `Bearer ${session.session.access_token}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to load TeamAra data.'); setData(result); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load TeamAra data.'); } finally { setLoading(false); } };
  useEffect(() => { if (tab === 'dashboard' || tab === 'partners') void load(''); }, [tab]);
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(query.trim()); void load(query.trim()); };
  const counts = useMemo(() => ({ total: data.members.length, active: data.members.filter((member) => member.active).length, inactive: data.members.filter((member) => !member.active).length, branches: new Set(data.members.map((member) => member.branch).filter(Boolean)).size }), [data.members]);
  return <div className="mx-auto max-w-[1500px] space-y-6">
    <section className="rounded-[30px] bg-[#0b3d59] p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#70d8fa]">TeamAra · Membership</p><h2 className="mt-3 text-3xl font-semibold">TeamAra management</h2><p className="mt-3 max-w-2xl text-[#b9cfdd]">Verify membership, review partner organisations and keep TeamAra records organised.</p></section>
    <section className="rounded-2xl bg-white p-2 shadow-sm"><div className="flex flex-wrap gap-2">{[['check','Member check'], ...(canEdit ? [['dashboard','Dashboard'], ['directory','Directory'], ['partners','Partners']] : [])].map(([id,label]) => <button key={id} onClick={() => setTab(id as typeof tab)} className={cn('rounded-xl px-4 py-2.5 text-sm font-semibold transition', tab === id ? 'bg-[#0b587b] text-white' : 'text-[#60758c] hover:bg-[#f2f7f9]')}>{label}</button>)}</div></section>
    {error && <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
    {tab === 'check' && <section className="grid gap-6 lg:grid-cols-[1fr_1.1fr]"><div className="rounded-[26px] bg-white p-6 shadow-sm sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf9fe] text-[#0b587b]"><Search className="h-5 w-5" /></div><h3 className="mt-5 text-2xl font-semibold">Check a TeamAra member</h3><p className="mt-2 text-sm leading-6 text-[#60758c]">Search by member name, IC number or membership ID. Enter at least two characters or four digits.</p><form onSubmit={submit} className="mt-6 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="e.g. Noor Atikah or membership ID" className="min-w-0 flex-1 rounded-xl bg-[#f4f8fa] px-4 py-3 text-sm outline-none ring-1 ring-transparent focus:ring-[#8cdbf7]" /><button className="rounded-xl bg-[#0b587b] px-5 py-3 text-sm font-semibold text-white">Search</button></form></div><div className="rounded-[26px] bg-[#edf9fe] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0b9aca]">Vendor guidance</p><h3 className="mt-3 text-xl font-semibold text-[#0b3d59]">Verify before applying benefits</h3><p className="mt-3 text-sm leading-6 text-[#526a80]">Confirm the member is active and check the expiry date before offering TeamAra discounts or benefits.</p><div className="mt-6 flex items-center gap-3 rounded-2xl bg-white p-4 text-sm text-[#29465a]"><CheckCircle2 className="h-5 w-5 text-emerald-500" />Member status is checked against the latest record.</div></div></section>}
    {tab === 'check' && submitted && <section><p className="mb-3 text-sm text-[#60758c]">{loading ? 'Searching…' : `${data.members.length} result${data.members.length === 1 ? '' : 's'} for “${submitted}”`}</p>{!loading && data.members.length === 0 && <div className="rounded-2xl bg-white p-8 text-center text-sm text-[#60758c]">No member record found. Please contact Klinik ARA 24 Jam for verification.</div>}<div className="grid gap-4 md:grid-cols-2">{data.members.map((member) => <div key={`${member.memberId}-${member.ic}`}><MemberCard member={member} /></div>)}</div></section>}
    {tab === 'dashboard' && <section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total members',counts.total,Users],['Active members',counts.active,CheckCircle2],['Inactive members',counts.inactive,XCircle],['Branches',counts.branches,BarChart3]].map(([label,value,Icon]) => <div key={String(label)} className="rounded-2xl bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-[#0b9aca]" /><p className="mt-4 text-sm text-[#60758c]">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>)}</div><DataTable title="Latest member records" rows={data.members.slice(0, 12).map((member) => ({ Name: member.name, 'Member ID': member.memberId, Branch: member.branch, Expiry: member.expiry, Status: member.active ? 'Active' : 'Inactive' }))} /></section>}
    {tab === 'directory' && <section><div className="rounded-2xl bg-white p-5 shadow-sm"><form onSubmit={submit} className="flex max-w-xl gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search directory by name, IC or ID" className="min-w-0 flex-1 rounded-xl bg-[#f4f8fa] px-4 py-3 text-sm outline-none" /><button className="rounded-xl bg-[#0b587b] px-5 py-3 text-sm font-semibold text-white">Search</button></form></div><DataTable title={`${data.members.length} member records`} rows={data.members.map((member) => ({ Name: member.name, IC: member.ic, Phone: member.phone, 'Member ID': member.memberId, Branch: member.branch, Expiry: member.expiry, Status: member.active ? 'Active' : 'Inactive' }))} /></section>}
    {tab === 'partners' && <section className="grid gap-6 lg:grid-cols-2"><DataTable title="TeamAra family" rows={data.family} /><DataTable title="Official vendors" rows={data.vendors} /></section>}
  </div>;
}

function MemberCard({ member }: { member: Member }) { return <article className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold uppercase">{member.name}</p><p className="mt-1 text-xs text-[#60758c]">Member ID: {member.memberId || 'Not recorded'}</p></div><span className={cn('rounded-full px-3 py-1 text-xs font-bold', member.active ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700')}>{member.active ? 'ACTIVE' : 'INACTIVE'}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-[#60758c]">Expiry</p><p className="mt-1 font-semibold">{member.expiry || 'Not recorded'}</p></div><div><p className="text-xs text-[#60758c]">Branch</p><p className="mt-1 font-semibold">{member.branch || 'Not recorded'}</p></div></div></article>; }
function DataTable({ title, rows }: { title: string; rows: Row[] }) { const columns = rows.length ? Object.keys(rows[0]) : []; return <section className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="p-5"><h3 className="text-lg font-semibold">{title}</h3></div>{!rows.length ? <p className="px-5 pb-6 text-sm text-[#60758c]">No records available.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-[#f7fafc] text-xs uppercase tracking-wider text-[#8aa0b3]"><tr>{columns.map((column) => <th key={column} className="px-5 py-3">{column}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,index) => <tr key={index} className="hover:bg-[#f8fcfe]">{columns.map((column) => <td key={column} className="px-5 py-3.5 text-[#526a80]">{row[column] || '—'}</td>)}</tr>)}</tbody></table></div>}</section>; }
